project:
  type: website

website:
  title: "RvCode"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/exiomius/
format:
  html:
    theme: darkly
    css: styles.css



